apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  # Environment
  DJANGO_ENVIRONMENT: "production"

  # Database
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: "5432"

  # Django settings
  DJANGO_ALLOWED_HOSTS: "*"

  # Email (SMTP) - Update with your email provider
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  DEFAULT_FROM_EMAIL: "noreply@touristmanagement.com"
  SERVER_EMAIL: "server@touristmanagement.com"
  ADMIN_EMAIL: "admin@touristmanagement.com"

  # Application settings
  DEFAULT_COMMISSION_RATE: "10.00"
  DEFAULT_CURRENCY: "USD"
  BOOKING_CANCELLATION_HOURS: "24"
  TIME_ZONE: "UTC"
  LANGUAGE_CODE: "en-us"

  # Security settings (production)
  SECURE_SSL_REDIRECT: "True"
  SESSION_COOKIE_SECURE: "True"
  CSRF_COOKIE_SECURE: "True"

  # Cache (optional - set if using Redis)
  # REDIS_URL: "redis://redis-service:6379/1"
