apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  POSTGRES_DB: "CHANGE_ME"
  POSTGRES_USER: "CHANGE_ME"
  POSTGRES_PASSWORD: "CHANGE_ME"
  SECRET_KEY: "CHANGE_ME"
  DEBUG: "True"
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
