apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  selector:
    app: django
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007 