apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

secretGenerator:
- name: django-secret
  behavior: replace
  envs:
  - secrets.env

patchesStrategicMerge:
- replica-patch.yaml
